import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Comment from '../components/Comment'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Project from '../components/Project'
import Skills from '../components/Skills'



export default function Home() {
  return (
    <div >
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
      <Hero/>
      <About/>
      <Skills/>
      <Project/>
      <Comment/>
      </main>

   
    </div>
  )
}




